canary:
  analysis:
    interval: 1m
    maxWeight: 60
    metrics:
      latency:
        interval: 1m
        threshold: 500
    stepWeight: 20
    threshold: 5
  enabled: false
  gatewayLabels: {}
  host: ""
  labels: {}
  progressDeadlineSeconds: 60
deploymentLabels: {}
env:
  PORT: "3003"
  NODE_ENV: "production"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ""
  NEXT_PUBLIC_BONDE_API_GRAPHQL_URL: "ws://api-graphql.staging.bonde.org/v1/graphql"
  BONDE_API_GRAPHQL_URL: "https://api-graphql.staging.bonde.org/v1/graphql"
  STRIPE_SECRET_KEY: ""
  NEXT_PUBLIC_INCUBATIONS_WIDGET_ID: "20292"
  NEXT_PUBLIC_MATERIALS_WIDGET_ID: "20293"
  NEXT_PUBLIC_DONATION_WIDGET_ID: "24146"
  NEXT_PUBLIC_NEWSLETTER_WIDGET_ID: "24147"
hpa:
  cpuTargetAverageUtilization: 80
  enabled: false
  labels: {}
  maxReplicas: 6
  memoryTargetAverageUtilization: 80
  minReplicas: 2
image:
  pullPolicy: IfNotPresent
  repository: 519061744633.dkr.ecr.us-east-1.amazonaws.com/nossas/nossas-org
  tag: 0.1.0
ingress:
  annotations: {}
  classAnnotation: ""
  labels: {}
jx:
  imagePullSecrets: []
  releaseCRD: true
jxRequirements:
  ingress:
    annotations: {}
    apiVersion: extensions/v1beta1
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    serviceType: ""
    tls:
      email: ""
      enabled: false
      production: false
      secretName: ""
knativeDeploy: false
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  probePath: ""
  successThreshold: 1
  timeoutSeconds: 1
podAnnotations: {}
podsLabels: {}
probePath: /
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  probePath: ""
  successThreshold: 1
  timeoutSeconds: 1
replicaCount: 1
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
service:
  annotations: {}
  externalPort: 80
  internalPort: 3003
  labels: {}
  name: nossas-org
  type: ClusterIP
serviceAccount:
  annotations: {}
  enabled: true
  labels: {}
  name: ""
