canary:
  analysis:
    interval: 1m
    maxWeight: 60
    metrics:
      latency:
        interval: 1m
        threshold: 500
    stepWeight: 20
    threshold: 5
  enabled: false
  gatewayLabels: {}
  host: ""
  labels: {}
  progressDeadlineSeconds: 60
deploymentLabels: {}
env: {}
envFrom:
  - secretRef:
      name: nossas-org
hpa:
  cpuTargetAverageUtilization: 80
  enabled: false
  labels: {}
  maxReplicas: 6
  memoryTargetAverageUtilization: 80
  minReplicas: 1
image:
  pullPolicy: IfNotPresent
  repository: draft
  tag: dev
ingress:
  annotations: {}
  classAnnotation: ""
  labels: {}
jx:
  imagePullSecrets: []
  releaseCRD: true
jxRequirements:
  ingress:
    annotations: {}
    apiVersion: extensions/v1beta1
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    serviceType: ""
    tls:
      email: ""
      enabled: false
      production: false
      secretName: ""
knativeDeploy: false
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 20
  probePath: ""
  successThreshold: 1
  timeoutSeconds: 30
podAnnotations: {}
podsLabels: {}
probePath: /
readinessProbe:
  failureThreshold: 10
  periodSeconds: 20
  probePath: ""
  successThreshold: 1
  timeoutSeconds: 5
replicaCount: 1
resources:
  limits:
    cpu: 400m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 128Mi
service:
  annotations: {}
  externalPort: 80
  internalPort: 3003
  labels: {}
  name: nossas-org
  type: ClusterIP
serviceAccount:
  annotations: {}
  enabled: true
  labels: {}
  name: ""
