apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          envFrom:
            - secretRef:
                name: nossas-org
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/typescript/pullrequest.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources: {}
        - name: build-npm-install
          resources: {}
        - name: build-npm-test
          resources: {}
        - name: check-registry
          resources: {}
        - image: gcr.io/kaniko-project/executor:debug-v1.3.0
          name: build-container-build
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=Dockerfile --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --build-arg=NODE_ENV --build-arg=NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY --build-arg=NEXT_PUBLIC_BONDE_API_GRAPHQL_URL --build-arg=BONDE_API_GRAPHQL_URL --build-arg=STRIPE_SECRET_KEY --build-arg=NEXT_PUBLIC_INCUBATIONS_WIDGET_ID --build-arg=NEXT_PUBLIC_MATERIALS_WIDGET_ID --build-arg=NEXT_PUBLIC_DONATION_WIDGET_ID --build-arg=NEXT_PUBLIC_NEWSLETTER_WIDGET_ID
        - name: promote-jx-preview
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
