apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: PORT
            value: "3003"
          - name: NODE_ENV
            value: "production"
          - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
            value: ""
          - name: NEXT_PUBLIC_BONDE_API_GRAPHQL_URL
            value: "ws://api-graphql.staging.bonde.org/v1/graphql"
          - name: BONDE_API_GRAPHQL_URL
            value: "https://api-graphql.staging.bonde.org/v1/graphql"
          - name: STRIPE_SECRET_KEY
            value: ""
          - name: NEXT_PUBLIC_INCUBATIONS_WIDGET_ID
            value: "20292"
          - name: NEXT_PUBLIC_MATERIALS_WIDGET_ID
            value: "20293"
          - name: NEXT_PUBLIC_DONATION_WIDGET_ID
            value: "24146"
          - name: NEXT_PUBLIC_NEWSLETTER_WIDGET_ID
            value: "24147"
          - name: NPM_CONFIG_USERCONFIG
            value: /tekton/home/npm/.npmrc
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/typescript/release.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          volumeMounts:
          - mountPath: /tekton/home/npm
            name: npmrc
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - name: jx-variables
          resources: {}
        - name: build-npm-install
          resources: {}
        - name: build-npm-test
          resources: {}
        - name: check-registry
          resources: {}
        - name: build-container-build
          resources: {}
        - name: promote-changelog
          resources: {}
        - name: promote-helm-release
          resources: {}
        - name: promote-jx-promote
          resources: {}
        volumes:
        - name: npmrc
          secret:
            optional: true
            secretName: npmrc
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
