apiVersion: v1
kind: Secret
metadata:
  name: nossas-org
type: Opaque
data:
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ""
  NEXT_PUBLIC_BONDE_API_GRAPHQL_URL: "d3NzOi8vYXBpLWdyYXBocWwvdjEvZ3JhcGhxbAo="
  BONDE_API_GRAPHQL_URL: "aHR0cHM6Ly9hcGktZ3JhcGhxbC92MS9ncmFwaHFsCg=="
  STRIPE_SECRET_KEY: ""
  NEXT_PUBLIC_INCUBATIONS_WIDGET_ID: "MjAyOTIK"
  NEXT_PUBLIC_MATERIALS_WIDGET_ID: "MjAyOTMK"
  NEXT_PUBLIC_DONATION_WIDGET_ID: "MjQxNDYK"
  NEXT_PUBLIC_NEWSLETTER_WIDGET_ID: "MjQxNDcK"
