name: Docker

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get tag
        id: repository
        run: echo  "::set-output name=tag::$(git describe --tags HEAD)"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nossas/nossas-org:${{ steps.repository.outputs.tag }}
          build-args: |
            NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
            NEXT_PUBLIC_BONDE_API_GRAPHQL_URL=${{ secrets.NEXT_PUBLIC_BONDE_API_GRAPHQL_URL }}
            BONDE_API_GRAPHQL_URL=${{ secrets.BONDE_API_GRAPHQL_URL }}
            STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
            NEXT_PUBLIC_INCUBATIONS_WIDGET_ID=${{ secrets.NEXT_PUBLIC_INCUBATIONS_WIDGET_ID }}
            NEXT_PUBLIC_INCUBATIONS_EN_WIDGET_ID=${{ secrets.NEXT_PUBLIC_INCUBATIONS_EN_WIDGET_ID }}
            NEXT_PUBLIC_MATERIALS_WIDGET_ID=${{ secrets.NEXT_PUBLIC_MATERIALS_WIDGET_ID }}
            NEXT_PUBLIC_MATERIALS_EN_WIDGET_ID =${{ secrets.NEXT_PUBLIC_MATERIALS_EN_WIDGET_ID }}
            NEXT_PUBLIC_DONATION_WIDGET_ID=${{ secrets.NEXT_PUBLIC_DONATION_WIDGET_ID }}
            NEXT_PUBLIC_DONATION_EN_WIDGET_ID=${{ secrets.NEXT_PUBLIC_DONATION_EN_WIDGET_ID }}
            NEXT_PUBLIC_NEWSLETTER_WIDGET_ID=${{ secrets.NEXT_PUBLIC_NEWSLETTER_WIDGET_ID }}
            NEXT_PUBLIC_NEWSLETTER_EN_WIDGET_ID=${{ secrets.NEXT_PUBLIC_NEWSLETTER_EN_WIDGET_ID }}
